### ISSUE TITLE
MyApp.setPic - divide by zero

### ISSUE THREAD

**Issue by elagin** [elagin/Ladle#35]
Lenovo A7000 (A7000-a):

- падение при просмотре хычинов
- что-то произошло, кажется при повороте экрана

`
at ru.crew4dev.forksnknife.MyApp.setPic(MyApp.java:626)
	at ru.crew4dev.forksnknife.Activites.ViewRecActivity.update(ViewRecActivity.java:177)
	at ru.crew4dev.forksnknife.Activites.ViewRecActivity.access$100(ViewRecActivity.java:28)
	at ru.crew4dev.forksnknife.Activites.ViewRecActivity$1.onGlobalLayout(ViewRecActivity.java:63)
`

https://play.google.com/apps/publish/?hl=ru&dev_acc=10976996020728051511#ErrorClusterDetailsPlace:p=ru.crew4dev.forksnknives&et=CRASH&sh=false&lr=LAST_7_DAYS&ecn=java.lang.ArithmeticException&tf=MyApp.java&tc=ru.crew4dev.forksnknife.MyApp&tm=setPic&nid&an&c&s=new_status_desc&ed=1485369403582

**Comment by elagin** [comment]
Решено: https://github.com/elagin/Ladle/commit/e4bc908b953eeb4f768f1180abe8cf26208335a9
